### ISSUE TITLE
Compatiblity with Codeception 2.3.x

### ISSUE THREAD

**Issue by raph007** [iamdevice/codeception-multidb#1]
Hello,

Is it compatible with Codeception 2.3.x?

**Comment by benphelps** [comment]
It is compatible with the current release as of posting this, `2.3.3`.

**Comment by mirao** [comment]
In Codeception 2.3.4 there is new method grabColumnFromDatabase().
If I need to use it with MultiDB, codeception-multidb must be internally upgraded, am I right?

**Comment by iamdevice** [comment]
@mirao you are right. I should upgrade my module and realise this new method.
